[profile.release]
strip = true

[workspace]

members = [
    "crates/meeting-indexer",
    "crates/common",
    "crates/frontend"
]

[workspace.dependencies]
tokio  = "1.23.0"
chrono = "0.4.23"
thiserror = "1.0.37"
serde = "1.0.150"
utoipa = "2.4.2"