[package]
name = "meeting-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
chrono = "0.4.23"
thiserror = "1.0.37"
reqwest = { version = "0.11.13", features = ["json"] }

serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"

rusqlite = "0.28.0"
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"

clap = { version = "4.0.29", features = ["derive"] }

actix-web = "4"

