export type Organization = 'AnonymousAlcoholics';

export interface Meeting {
	/// A unique id generated by the frontend.
	id: number;

	longitude: number;
	latitude: number;
	org: Organization;

	country: string | null;
	region: string | null;
	distance: number | null;
	conferenceUrl: string | null;
	online: boolean;
	name: string;

}
