export type Organization = 'AnonymousAlcoholics';

export interface MeetingPosition {
    longitude: number;
    latitude: number;
}

export interface Meeting {
    /// A unique id generated by the frontend.
    id: number;

    position: MeetingPosition | null;
    org: Organization;

    country: string | null;
    region: string | null;
    distance: number | null;
    conferenceUrl: string | null;
    online: boolean;
    name: string;

}
